
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: SABRIAN  ## put your name
title: 'Mahasiswa Sistem Informasi, UIN Suska Riau'  ## your title
location: Pekanbaru, Riau Indonesia


## Social Profiles
facebook: https://www.facebook.com/sabrian.sabrian.5439  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
